apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  type: LoadBalancer  # Adjust type if needed
  ports:
  - protocol: TCP
    port: 80  # External port (adjust if needed)
    targetPort: 5000  # Port the container exposes
