name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: amogh9792/wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set KUBECONFIG environment variable
      run: |
        # Download the kubeconfig from the secret and store it temporarily
        echo ${{ secrets.KUBECONFIG }} | base64 -d > /tmp/kubeconfig

        # Set the KUBECONFIG environment variable to point to the temporary file
        export KUBECONFIG=/tmp/kubeconfig

        # Optional: Verify kubeconfig content (remove for production)
        # kubectl config view

    - name: Install kubectl (optional, if not pre-installed)
      run: |
        curl -LO "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/wiscow_deployment.yaml
        kubectl apply -f k8s/wiscow_service.yaml
